[package]
name = "banking-trace-tool"
version = "0.1.0"
authors = ["Andrew Fitzgerald <apfitzge@gmail.com>"]
repository = "https://github.com/apfitzge/banking-trace-tool"
edition = "2021"

[dependencies]
bincode = { version = "1.3.3" }
clap = { version = "4.3.11", features = ["derive"] }
prio-graph = { git = "https://github.com/apfitzge/prio-graph.git", rev = "fcf06ed020d6dd5325122789cd3633547c6d023c" }
serde = { version = "1.0.190" }
serde_json = { version = "1.0.108" }
solana-core = { version = "1.17.3" }
solana-sdk = { version = "1.17.3" }
solana-alt-store = { git = "https://github.com/apfitzge/solana-alt-store.git" }
